mypage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rfidesign.urls')),
    path('', include('get_in_touch.urls')),
    path('', include('our_store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

our_store/urls.py
from django.urls import path

from .views import(        
StoreView,
AllProductsView,
ProductDetailView,
AddToCartView,
MyCartView,
ManageCartView,
EmptyCartView,
CheckoutView,
CustomerRegistrationView,
CustomerLogoutView,
CustomerLoginView,
CustomerProfileView,
CustomerOrderDetailView,
AdminLoginView,
AdminHomeView,
AdminOrderDetailView,
AdminOrderListView,
AdminOrderStatusChangeView,
SearchView,
AdminProductListView,
AdminProductCreateView,
ForgotPasswordView,
PasswordResetView,
AdminLogoutView
)

app_name = 'our_store'
urlpatterns = [
        path('store/', StoreView.as_view(), name='store'),
        path('all-products/', AllProductsView.as_view(), name='allproducts'),
        path('product/<slug:slug>/', ProductDetailView.as_view(), name='productdetail'),
        path('add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
        path('my-cart/', MyCartView.as_view(), name='mycart'),
        path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name='managecart'),
        path('empty-cart/', EmptyCartView.as_view(), name='emptycart'),
        path('checkout/', CheckoutView.as_view(), name='checkout'),
        
        path('register/', CustomerRegistrationView.as_view(), name='customerregistration'),
        path('logout/', CustomerLogoutView.as_view(), name='customerlogout'),
        path('login/', CustomerLoginView.as_view(), name='customerlogin'),
        path('forgot-password/', ForgotPasswordView.as_view(), name='forgotpassword'),
        path('password-reset/<email>/<token>/', PasswordResetView.as_view(), name='passwordreset'),
        
        path('profile/', CustomerProfileView.as_view(), name='customerprofile'),
        path('profile/order-<int:pk>/', CustomerOrderDetailView.as_view(), name='customerorderdetail'),
        
        path('search/', SearchView.as_view(), name='search'),

        # Admin Side pages

        path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
        path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
        path('admin-order/<int:pk>/', AdminOrderDetailView.as_view(), name='adminorderdetail'),
        path('admin-logout/', AdminLogoutView.as_view(), name='adminlogout'),


        path('admin-all-orders/', AdminOrderListView.as_view(), name='adminorderlist'),
        path('admin-order-<int:pk>-change/', AdminOrderStatusChangeView.as_view(), name='adminorderstatuschange'),

        path('admin-product/list/', AdminProductListView.as_view(), name='adminproductlist'),
        path('admin-product/add/', AdminProductCreateView.as_view(), name='adminproductcreate'),



]

our_store/models.py
from django.db import models


from django.contrib.auth.models import User

from django.urls import reverse


from django.contrib.auth import get_user_model as user_model


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="admin")
    mobile = models.CharField(max_length=20)

    def __str__(self):
       return self.user.username

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(null=True,blank=True)
    password = models.CharField(max_length=100,null=True)
    username = models.CharField(max_length=25,null=True)


    def __str__(self):
       return self.full_name
    
    def get_absolute_url(self):
         return reverse("our_store:store")

    
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=200, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
            return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
            return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)

ORDER_STATUS = (
   ("Order Received", "Order Received"),
   ("Order Processing", "Order Processing"),
   ("On the way", "On the way"),
   ("Order Canceled", "Order Canceled"),
)

class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, default=None)
    subtotal = models.PositiveIntegerField()
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(null=True,blank=True)
    
    def __str__(self):
           return "Order: " + str(self.id)

our_store/views.py
from audioop import reverse
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import View, TemplateView, CreateView, FormView, DetailView, ListView
from our_store.forms import CustomerRegistrationForm, CustomerLoginForm, ForgotPasswordForm, PasswordResetForm, ProductForm, CheckoutForm
from .models import Order, Cart, Product, Category,CartProduct, User, Customer, Admin, ORDER_STATUS, ProductImage
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout

from django.core.mail import send_mail
from django.conf import settings




class EcomMixin(object):
    def dispatch(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id")
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            if request.user.is_authenticated and request.user.customer:
                cart_obj.customer = request.user.customer
                cart_obj.save()
        return super().dispatch(request, *args, **kwargs)

class StoreView(EcomMixin, TemplateView):
    template_name ="store.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_products = Product.objects.all().order_by("-id")
        paginator = Paginator(all_products, 6)
        page_number = self.request.GET.get('page')
        print(page_number)
        product_list = paginator.get_page(page_number)
        context['product_list'] = product_list
        return context

class AllProductsView(EcomMixin, TemplateView):
    template_name ="allproducts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = Category.objects.all()
        return  context

class ProductDetailView(EcomMixin, TemplateView):
    template_name ="productdetail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        product.view_count += 1
        product.save()
        context['product'] = product
        return  context 

class AddToCartView(EcomMixin, TemplateView):
    template_name = "addtocart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #get product id from requested url
        product_id = self.kwargs['pro_id']
        # get product
        product_obj = Product.objects.get(id=product_id)
        # check if cart exists
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(
                product=product_obj)
        # items already exixst in the cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
        # new item is added in cart
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
                cart_obj.total += product_obj.selling_price
                cart_obj.save()

        else:
            cart_obj = Cart.objects.create(total=0)
            #self.request.session['cart_id'] = cart_obj.id
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
            cart_obj.total += product_obj.selling_price
            cart_obj.save()
        return context

class ManageCartView(EcomMixin, View):
    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs["cp_id"]
        action = request.GET.get("action")
        cp_obj = CartProduct.objects.get(id=cp_id)
        cart_obj = cp_obj.cart
        
        if action == "inc":
            cp_obj.quantity += 1
            cp_obj.subtotal += cp_obj.rate
            cp_obj.save()
            cart_obj.total += cp_obj.rate
            cart_obj.save()

        elif action == "dcr":
            cp_obj.quantity -= 1
            cp_obj.subtotal -= cp_obj.rate
            cp_obj.save()
            cart_obj.total -= cp_obj.rate
            cart_obj.save()
            if cp_obj.quantity <=0:
                cp_obj.delete()
                
        elif action == "rmv":
            cart_obj.total -= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()
        else:
            pass
        return redirect('our_store:mycart')

class EmptyCartView(EcomMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = request.session.get('cart_id', None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
            cart.cartproduct_set.all().delete()
            cart.total = 0
            cart.save()
        return redirect('our_store:mycart')



class MyCartView(EcomMixin, TemplateView):
    template_name= 'mycart.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id', None)
        print(cart_id)
        
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
            
        else:
            cart = None
        context['cart'] = cart

        return context

class CheckoutView(EcomMixin, CreateView):
    template_name= 'checkout.html'
    form_class = CheckoutForm
    success_url: reverse_lazy('our_store:store')

    def dispatch(self, request,  *args, **kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return redirect("/login/?next=/checkout/")
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data( **kwargs)
        cart_id = self.request.session.get('cart_id', None)

        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        context['cart'] = cart_obj
        return context
    
    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            form.instance.cart = cart_obj
            form.instance.subtotal = cart_obj.total
            form.instance.discount = 0
            form.instance.total = cart_obj.total
            form.instance.order_status = "Order Received"
            del self.request.session['cart_id']
        else:
            return redirect("our_store:store")
        return super().form_valid(form)

class CustomerRegistrationView(CreateView):
    template_name= 'customerregistration.html'
    form_class = CustomerRegistrationForm

    
    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)
    
    def get_success_url(self):
        if'next' in self.request.GET:
            next_url = self.request.GET.get('next')
            return next_url
        else:
            return self.success_url



class CustomerLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("our_store:store")

        
class CustomerLoginView(FormView):
    template_name = 'customerlogin.html'
    form_class = CustomerLoginForm
    success_url = "/store/"

    # form_valid method is a type of post method and is available in ctreatview formview and updateview

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None and Customer.objects.filter(user=user).exists():
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {'form': self.form_class, 'error': 'Invalid credentials'})
        return super().form_valid(form)

    def get_success_url(self):
        if'next' in self.request.GET:
            next_url = self.request.GET.get('next')
            return next_url
        else:
            return self.success_url

    
class ForgotPasswordView(FormView):
    template_name = 'forgotpassword.html'
    form_class = ForgotPasswordForm
    success_url = "/forgot-password/?m=s"

    def form_valid(self, form):
        # get email from user
        email = form.cleaned_date.get("email")
        # get current host ip/domain
        url = self.request.METAL['HTTP_HOST']
        # get customer and then user
        customer = Customer.objects.get(user__email=email)
        user = customer.user
        # send email to ther user with email
        text_content = 'Please Click the link below to reset your password.'
        html_content = url + "/password-reset/" + \
            "/" + password_reset_token.make_token(user) + "/"
        send_mail(
            'Password Reset Link | Django Ecommerce',
            text_content + html_content,
            settings.EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )
        return super().form_valid(form)

class PasswordResetView(FormView):
    template_name = 'passwordreset.html'
    form_class = PasswordResetForm
    success_url = "/login/"

our_store/templates/allproducts.html
{% extends 'base.html' %}
{% load static %}
    
    
        {% block title %}
            <title>allproducts</title>
        {% endblock title %}
    
           
           
        {% block content %}
        <br>
           <div class="sixthin wide column">
                <div class="ui fluid card" style="background-color: rgb(201, 224, 238);">
                    <div class="content">
                        <div class="btn-group btn-group-justified" >
                            <centre><h3>ALL CATEGORIES </h3></centre>
                            <a href="{% url 'our_store:store' %}" class="btn btn-primary">Back to Our Store</a>
                            <!--<a href="{% url 'our_store:mycart' %}" class="btn btn-primary">My Cart</a>-->
                            {% if request.user.customer %}
                        Welcome {{request.user.username}}!!
                        <a href="{% url 'our_store:mycart' %}" class="btn btn-primary">My Cart</a>
                        <a href="{% url 'our_store:customerprofile' %}" class="btn btn-primary">My Profile</a>
                        <a href="{% url 'our_store:customerlogout' %}" class="btn btn-primary">Logout</a>
                        {% else %}
                       

                        <a href="{% url 'our_store:customerregistration' %}" class="btn btn-primary">Create an account</a>
                        <a href="{% url 'our_store:customerlogin' %}" class="btn btn-primary">Login</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            {% for cat in allcategories %}
            <strong><h5>{{cat.title}}</h5></strong><hr>
            <div class="row">
                <!--<div class="box-element product">-->
                    {% for p in cat.product_set.all %}
                    <div class="col-md-3">
                        <div class="m-4">
                            <strong><h6><a href="{% url 'our_store:productdetail' p.slug %}">{{p.title}}</a></h6></strong>                           
                            <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 
                            2500; object-fit:cover;"> 
                            <h5 style="display: inline-block; float: right; "><strong><p>Price: <strike>R{{p.marked_price | floatformat}}</strike>  | R 
                            {{p.selling_price | floatformat}}</p></strong></h5>
                            <a href="{% url 'our_store:addtocart' p.id %}" class="btn btn-outline-secondary add-btn update-cart">Add To Cart</a>
                        </div>
                    </div> 
                    {% endfor %}   
                </div>
            {% endfor %}
            </div>
        
{% endblock content %}
            
            
    

our_store/templates/mycart.html
{% extends 'base.html' %}
{% load static %}

        {% block title %}
        <title>my cart</title>
        {% endblock %}

       
        {% block content %}
        <br>
        <div class="row">
            <div class="ui fluid card" style="background-color: rgb(201, 224, 238);">
                <div class="content">
                    <div class="btn-group btn-group-justified" >
                        <centre><h3>My Cart </h3></centre>
                        <a href="{% url 'our_store:store' %}" class="btn btn-primary">Back to Our Store</a>
                        <a href="{% url 'our_store:allproducts' %}" class="btn btn-primary">All Products</a>
                        {% if request.user.customer %}
                        Welcome {{request.user.username}}!!
                        <a href="{% url 'our_store:customerlogout' %}" class="btn btn-primary">Logout</a>
                        <a href="{% url 'our_store:customerprofile' %}" class="btn btn-primary">My Profile</a>

                        {% else %}
                        <a href="{% url 'our_store:customerregistration' %}" class="btn btn-primary">Create an account</a>
                        <a href="{% url 'our_store:customerlogin' %}" class="btn btn-primary">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6 mx-auto">
                <form action="" method="GET">
                    <input type="text" name="keyword" placeholder="Search product here..." required>
                    <button>Search product</button>
                </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-8">
                <h3>Items in my cart</h3><hr>
                <table class="table">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>Product</th>
                            <th>Rate</th>
                            <th>Quantity</th>
                            <th>Subtotal</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                       {% for cp in cart.cartproduct_set.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{cp.product.title}}</td>
                                <td>{{cp.rate}}</td>
                                <td>{{cp.quantity}}</td>
                                <td>{{cp.subtotal}}</td>
                                <td>
                                    <a href="{% url 'our_store:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                                    <a href="{% url 'our_store:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                                    <a href="{% url 'our_store:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <th colspan='4' class='text-rigth'>Total</th>
                            <th>R{{cart.total}}</th>
                            {% if cart.cartproduct_set.all  %}
                            <th><a href="{% url 'our_store:emptycart' %}">Empty Cart</a></th>
                            {% endif %}
                        </tr>
                        <tr>
                            {% if cart.cartproduct_set.all  %}
                            <th><a class="btn btn-info" href="{% url 'our_store:checkout' %}">Checkout</a></th>
                            {% endif %}
                        </tr>


                    </tbody>
                </table>
            </div>
        </div>
           
            
            
        
      
       
        {% endblock content %}

our_store/templates/productdetail.html
{% extends 'base.html' %}
{% load static %}

        {% block title %}
        <title>{{product.title}}</title>
        {% endblock %}

       
        {% block content %}
        
        <br>
        <div class="row">
            <div class="sixthin wide column">
                <div class="ui fluid card" style="background-color: rgb(201, 224, 238);">
                    <div class="content">
                        <div class="btn-group btn-group-justified" >
                            <centre><h3>ALL CATEGORIES </h3></centre>
                            <a href="{% url 'our_store:store' %}" class="btn btn-primary">Back to Our Store</a>
                            <a href="{% url 'our_store:allproducts' %}" class="btn btn-primary">All Products</a>
                            <a href="" class="btn btn-primary">My Cart</a>
                            {% if request.user.customer %}
                        Welcome {{request.user.username}}!!
                        <a href="{% url 'our_store:mycart' %}" class="btn btn-primary">My Cart</a>
                        <a href="{% url 'our_store:customerprofile' %}" class="btn btn-primary">My Profile</a>
                        <a href="{% url 'our_store:customerlogout' %}" class="btn btn-primary">Logout</a>
                        {% else %}
                        <a href="{% url 'our_store:customerregistration' %}" class="btn btn-primary">Create an account</a>
                        <a href="{% url 'our_store:customerlogin' %}" class="btn btn-primary">Login</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <h3>Product: {{product.title}}</h3><hr>
        <div class="row">
            <div class="col-md-4">
                <img src="{{product.image.url}}" alt="" class="img-fluid">
                <div class="row">
                    {% for pi in product.productimage_set.all %}
                    <div class="col-md-4 p-3">
                        <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">    
                        </a>
                    </div>
                    {% endfor %}

                </div> 
            </div>
            <div class="col-md-8">
                <h5>{{product.title}} (Viewed {{product.view_count}} times)</h5>
                <h5>Category: {{product.category}}</h5>
                <h5><strong><p>Price: <strike>R{{product.marked_price}}</strike>  | R {{product.selling_price}}</p></strong></h5>
                <a href="{% url 'our_store:addtocart' product.id %}" class="btn btn-outline-secondary add-btn update-cart">Add To Cart</a>

   
                <hr>
                <p class="text-info">Warranty: {{product.category}}</p>
                <p class="text-info">Return Policy: {{product.return_policy}}</p>
                <hr>
                <p>{{product.description}}</p>
            </div>
        </div>
           
            
            
        
      
       
        {% endblock content %}

our_store/templates/store.html
{% extends 'base.html' %}
{% load static %}

        {% block title %}
        <title>store</title>
        {% endblock %}

       
        {% block content %}
        <br>
        <div class="row">
            <div class="sixthin wide column">
                <div class="ui fluid card" style="background-color: rgb(201, 224, 238);">
                    <div class="content">
                        
                            <div class="btn-group btn-group-justified">
                                <a href="{% url 'our_store:allproducts' %}" class="btn btn-primary">All Products</a>
                                <!--<a href="{% url 'our_store:mycart' %}" class="btn btn-primary">My Cart</a>-->

                                {% if request.user.customer %}
                                <strong>Welcome{{request.user.username}}!!</strong>
                                <a href="{% url 'our_store:mycart' %}" class="btn btn-primary">My Cart</a>
                                <a href="{% url 'our_store:customerprofile' %}" class="btn btn-primary">My Profile</a>
                                <a href="{% url 'our_store:customerlogout' %}" class="btn btn-primary">Logout</a>
                                {% else %}
                                

                                <a href="{% url 'our_store:customerregistration' %}" class="btn btn-primary">Create an account</a>
                                <a href="{% url 'our_store:customerlogin' %}" class="btn btn-primary">Login</a>
                                

                                {% endif %}
                            </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6 mx-auto">
                <form action="{% url 'our_store:search' %}" method="GET">
                    <input type="text" name="keyword" placeholder="Search product here..." required>
                    <button>Search product</button>
                </form>
            </div>
        </div>
        
        <hr>
        <div class="row">
            {% for p in product_list %}
            <div class="col-lg-4">
                <strong><h6><a href="{% url 'our_store:productdetail' p.slug %}">{{p.title}}</a></h6></strong>               
                <img class="thumbnail" src="{{p.image.url}}">
                <hr>
                <div class="box-element product">
                    <a href="{% url 'our_store:addtocart' p.id %}" class="btn btn-outline-secondary add-btn update-cart">Add To Cart</a>
                    <a class="btn btn-outline-success" href="{% url 'our_store:productdetail' p.slug %}">View</a>
                        <!--<h5 style="display: inline-block; float: right; "><strong>R{{selling.price | floatformat}}</strong></h5>-->
                        <h5 style="display: inline-block; float: right; "><strong><p>Price: <strike>R{{p.marked_price | floatformat}}</strike>  | R 
                            {{p.selling_price | floatformat}}</p></strong></h5>
                </div>
            </div>
            {% endfor %}
        </div>
        <br>
        <div class="row">
            <nav aria-label="...">
                <ul class="pagination">
                    {% if product_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
                    </li>
                    {% else %}
                    <li class="page-link disable">
                        <a class="page=link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% endif %}

                    {% for i in product_list.paginator.page_range %}
                    {% if i == product_list.number %}
                    <li class="page-item active"><a class="page-link">{{i}}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?pages={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if product_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disable="true">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
           
            
            
        
      
       
        {% endblock content %}