mypage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rfidesign.urls')),
    path('', include('get_in_touch.urls')),
    path('', include('our_store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

our_store/urls.py
from django.urls import path

from .views import(        
StoreView,
AllProductsView,
ProductDetailView,
AddToCartView,
MyCartView,
ManageCartView,
EmptyCartView,
CheckoutView,
CustomerRegistrationView,
CustomerLogoutView,
CustomerLoginView,
CustomerProfileView,
CustomerOrderDetailView,
AdminLoginView,
AdminHomeView,
AdminOrderDetailView,
AdminOrderListView,
AdminOrderStatusChangeView,
SearchView,
AdminProductListView,
AdminProductCreateView,
ForgotPasswordView,
PasswordResetView,
AdminLogoutView
)

app_name = 'our_store'
urlpatterns = [
        path('store/', StoreView.as_view(), name='store'),
        path('all-products/', AllProductsView.as_view(), name='allproducts'),
        path('product/<slug:slug>/', ProductDetailView.as_view(), name='productdetail'),
        path('add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
        path('my-cart/', MyCartView.as_view(), name='mycart'),
        path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name='managecart'),
        path('empty-cart/', EmptyCartView.as_view(), name='emptycart'),
        path('checkout/', CheckoutView.as_view(), name='checkout'),
        
        path('register/', CustomerRegistrationView.as_view(), name='customerregistration'),
        path('logout/', CustomerLogoutView.as_view(), name='customerlogout'),
        path('login/', CustomerLoginView.as_view(), name='customerlogin'),
        path('forgot-password/', ForgotPasswordView.as_view(), name='forgotpassword'),
        path('password-reset/<email>/<token>/', PasswordResetView.as_view(), name='passwordreset'),
        
        path('profile/', CustomerProfileView.as_view(), name='customerprofile'),
        path('profile/order-<int:pk>/', CustomerOrderDetailView.as_view(), name='customerorderdetail'),
        
        path('search/', SearchView.as_view(), name='search'),

        # Admin Side pages

        path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
        path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
        path('admin-order/<int:pk>/', AdminOrderDetailView.as_view(), name='adminorderdetail'),
        path('admin-logout/', AdminLogoutView.as_view(), name='adminlogout'),


        path('admin-all-orders/', AdminOrderListView.as_view(), name='adminorderlist'),
        path('admin-order-<int:pk>-change/', AdminOrderStatusChangeView.as_view(), name='adminorderstatuschange'),

        path('admin-product/list/', AdminProductListView.as_view(), name='adminproductlist'),
        path('admin-product/add/', AdminProductCreateView.as_view(), name='adminproductcreate'),



]

templates/main/agriculture.html
{% extends 'base.html' %}


{% load static %}


    {% block title %}

    <title>agriculture</title>
    {% endblock title %}
    <br>
    {% block content %}
    <br>
    
        <div class="ui grid">
            <h1>RFID in Agriculture</h1>
            <div class="row">
                <div class="col-md-7">
                    <img src={% static 'image/05-RFID-Smart-Farming-Agriculture-980x653 (1).jpeg' %}>
                </div>
                <div class="col-md-6">
                    
                    <hr>
                    <strong></strong><h3>How RFID in Farming and Agriculture Improves Global Food Production</h3>
                    <h1>RFID in farming helps monitor livestock, crops, and the environmental conditions that influence yields</h1>
                    <strong>
                    <p> 1. Enabling Farm Automation and Control</p>
                    <p> 2. Recording Climate Information for Improved Yields</p>
                    <p> 3. Increasing Agricultural Productivity with RFID Tagging</p>
                    <p> 4. Livestock Monitoring for Health and Disease Detection</p>
                    <p> 5. Keeping Consumers Informed About their Food</p>
                    </strong>
                   
                </div>
            </div>
        </div>
    {% endblock content %}

templates/main/food.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>food</title>
    {% endblock title %}

    {% block content %}
    <center><strong>
        <h1>RFID in Food</h1>
    </strong></center>
    <hr>
    
        <div class="ui grid">
            <div class="row">
                <div class="col-md-6">
                    <!--<img src={% static 'image/6-Axis-Robot-1.jpg' %}>--> 
                    <img src={% static 'image/foodimages.jpg' style="width:50%;height:60%;" %}>
                    <img src={% static 'image/fruitimages.jpg' style="width:50%;height:60%;" %}>
                    
                   
                </div>  
                <div class="col-md-6">
                    <h3>Mature RFID technology is ready to take on the food industry</h3>
                </div>  
            </div>
            <div class="row">
                <div class="col-md-6">
                    <img src={% static 'image/food2images.jpg' style="width:50%;height:60%;" %}>
                    <img src={% static 'image/download (1).jpg' style="width:50%;height:60%;" %}>
                </div>
                <div class="col-md-6">
                    <strong>
                        Radio frequency identification (RFID) has become established as a dominant force in the apparel industry,
                        with the technology finally approaching mass adoption after years of threatening to.
                        The technology involves tags or “labels” that emit a small radio frequency, allowing radio
                        stock counts that are both highly accurate and incredibly fast compared to traditional methods. 
                        The result of this is a very up to date, or even real-time, view of stock. The main use cases responsible for 
                        the technology’s success include the increased process efficiency, superior inventory management and the enablement 
                        of seamless omnichannel services.
                    </strong>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <img src={% static 'image/download.jpg' style="width:50%;height:60%;" %}>
                    <img src={% static 'image/food3images.jpg' style="width:50%;height:60%;" %}>
                </div>
                <div class="col-md-6">
                    <strong>
                        That’s the story of RFID in apparel, but what about other retail industries? After years of 
                        technical roadblocks that have kept the technology out of other markets, the technology has 
                        matured to a point where new industries are RFID-viable for the first time ever. The beauty and 
                        cosmetics industry is beginning to take notice of RFID, and perhaps now food retailers should do the same.
                        Why? Because modern RFID is so well positioned to tackle the food industry’s unique challenges,
                        like optimising inventory, minimising food waste and increasing the traceability of the supply chain.
                        Whilst this sounds great, the limitations of the technology that we mentioned earlier have 
                        historically meant RFID just wasn’t viable for the food market. As well as liquid and metallic products 
                        traditionally interfering with the RFID signals, the food industry’s drastically lower average article price 
                        compared to the apparel industry were significant roadblocks. But this changing…
                    </strong>
                </div>
            </div>
        </div>
        
{% endblock content %}

templates/main/hospitality.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
    <center><strong>
        <h1>RFID in Hospitality</h1>
    </strong></center>
    
    <hr>
    {% block title %}
    {% endblock title %}
                <div class="ui grid">
                    <br>
                    <div class="row">
                        <div class="col-md-6">
                            <img src={% static 'image/hospitalityimages2.jpg' %}>
                            <img src={% static 'image/hospitalityimages2.jpg' %}>
                        </div>
                        <div class="col-md-6">
                            <p>
                                <h1>HOTELS TOO NEED BETTER INVENTORY MANAGEMENT</h1> 
                            
                            When talking about RFD, we all acknowledge the positive impact of RFID in asset-heavy industries
                            like retail and logistics. However, there is one sector that is just beginning to realize not 
                            using RFID is a huge missed opportunity. Hospitality has been constantly engaging with innovative
                            technologies to enhance the customer experience and stand out in a competitive environment. 
                            Therefore, it’s not surprising that more and more hotels are adopting RFID solutions.
                            In fact, RFID or Radio-Frequency Identification is currently the best technology available for
                            asset tracking and inventory management. Hotels deal with hundreds of assets that are constantly 
                            moving in and out of their premises and can highly benefit from a smart inventory.
                            </p>
            
                            <hr>
                        </div>
                        <div class="col-md-6">
                            <img src={% static 'image/hospitalityimages3.jpg' %}>
                            <img src={% static 'image/hospitalityimages4.jpg' %}>

                        </div>
                        <div class="col-md-6">
                            <strong>WITH SMART INVENTORY MANAGEMENTS, HOTELS CAN:</strong>
                            <br/>
                            <p>Keep track of each item in their inventory.</p>
                            <p>Optimize maintenance and replacement.</p>
                            <p>Discourage theft and improve safety.</p>
                            <p>Reduce losses and cut waste.</p>
                    </div>
                </div>
        
{% endblock content %}

templates/main/industries.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br/>
    {% block title %}
    <title>industries</title>
    {% endblock title %}
          <center>
          <h1>Industries</h1>
          <strong>
          </center>
          <hr>
        <div class="ui grid" style="font-size: 20px;">
          <div class="row">
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
              <!--<div class="ui fluid card" style="background-color: rgb(201, 224, 238);">-->
                <div class="content">Who is RFID for?</div>
              </div>
            </div>
            <div class="eight wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">
                  RFID has been adoubted by various industries in a very short space of time.
                </div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content"> RFID works efficient in all Industries.</div>
              </div>
            </div>
          </div>
          <br/><br/><br/><br/>
          <div class="row">
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">AGRICULTURE</div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">HOSPITALITY</div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">
                  FOOD
                </div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content"> LOGISTICS</div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">MANUFACTURING</div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">MEDICAL</div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">
                  PHARMACEUTICAL
                </div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content"> RETAIL</div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content"></div>
              </div>
            </div>
            <div class="eight wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content">
                  SUPPLY CHAIN
                </div>
              </div>
            </div>
            <div class="four wide column">
              <div class="ui fluid card" style=" background-color: rgba(167, 150, 212, 0.4); ">
                <div class="content"> </div>
              </div>
            </div>
          </div>
        </div>
{% endblock content %} 

templates/main/logistics.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% block title %}
    <title>Logistics</title>
    {% endblock title %}
    <br>
    <center><strong>
        <h1>Logistics</h1>
    </strong></center>
    <hr>
    <div class="ui grid">
        <br>
        <div class="row">
            <div class="col-md-6">
                <img src={% static 'image/istockphoto-1138429558-612x612.jpg' %}>
            </div>
            <div class="col-md-6">
                <img src={% static 'image/istockphoto-1138429558-612x612.jpg' %}>
            </div>
            <div class="col-md-8">
                <p>
                    <strong>RFID technology is currently making a huge difference in the transportation sector due to its 
                        ability to support an incredibly versatile range of applications. Why is RFID being used so much 
                        in this sector in particular, and how could you make the most of it?</strong>
                    </div>
                </p>

                <br><br>
                <p>
                    <h3>Automated Ticketing for Public Transport</h3>
                    This clever use of RFID is not only great for speeding up the process of issuing tickets for the transport company 
                    themselves, but it also benefits their consumers. How so? As we discussed before, RFID technology doesn’t require a 
                    line of sight to be used and so it is extremely versatile and quick to use. This helps to reduce queuing times and 
                    human errors which in turn will maximize customer satisfaction!
                </p>
                <hr>
                <p>
                    <h3>RFID tags on vehicles</h3>
                            This method is often used to track when vehicles arrive back at the depot, this then accurately keeps a record of the 
                            available vehicles at any given time! Other applications include vehicle identification when arriving at a site. 
                            These two ways of using RFID greatly contribute to faster business processes, planning and in turn the overall success
                            of the whole transportation company.
                </p>
                
            </div>
        </div>
    </div>
        
{% endblock content %}

templates/main/manufacturing.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>manufacturing</title>
    {% endblock title %}

  
    
    {% block content %}
    <br>
    <h1>RFID in Manufacturing</h1>
    <hr>
        
        <div class="ui grid">
            <br>
            <div class="row">
                <div class="col-md-6">
                    <img src={% static 'image/mc3390xr-photography-application-manufacturing-man-pushing-keypad-print-300dpi-1024x690 (1).jpeg' %}>
                </div>
                <div class="col-md-7">
                <strong>
                    <p>
                        The use of RFID technology in the manufacturing process offers many benefits to a manufacturing
                 process. RFID can reduce the amount of paper needed to create the product, it allows for better 
                 tracking of inventory, more accurate status of WIP, fewer manufacturing errors and a higher 
                 quality product. Capturing the benefits of RFID technology in this arena is relatively easy 
                 compared to some other applications because the RFID tags can be of the passive type and can be
                 reused. It makes the value proposition very attractive for that reason alone.
                     </p>
                </strong>    
                </div>
            </div>
        </div>
{% endblock content %}

templates/main/medical.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>medical</title>
    {% endblock title %}
    {% block content %}
    <br/>
    <h1>RFID in Medical</h1>
        <hr>
        <div class="ui grid">
            <br>
            <div class="row">
                <div class="col-md-6">
                    <img src={% static 'image/medical .jpg' %}>
                </div>
                <div class="col-md-6">
                    <p>
                        In this industry, there is no room for error. You need to have knowledge and control of your critical assets and medical
                        equipment, no matter what. In the health and aged care sector you need to provide a high level of service and safety 
                        for your patients, and guests, and be more diligent than ever in the tracking and accountability of Portable Medical 
                        Equipment PME and PPE control. There’s a lot riding on every decision and action, and there’s a lot to lose.
                    </p>
    
                    <hr>
                    <p>
                        <strong>When it comes to medical equipment tracking and hospital asset management, certainty matters.</strong> The healthcare and aged 
                        care sector are one of the most highly regulated industries in the world. Good governance, compliance and risk mitigation
                        are critical to your business. Your employees rely on having the right equipment in good condition for those that they
                        serve. In your world, it could be the difference between life and death.
                    </p>
                </div>
            </div>
        </div>
{% endblock content %}

templates/main/navbar.html
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<body>
  <nav class="navbar navbar-expand-lg" style="background-color: navy;">
    <a class="navbar-band" href="">
      <img src="{% static 'image/Logo001.jpg'%}" style="width:150px;height: 70px">
    </a>

      <span style="position: absolute; left: 15%">
        <button class="button-73" role="button">
          <a href="{% url 'home-view' %}">Home</a>
        </button>
      </span>

      <ul class="main-nav" style="position:absolute;left:45%">
        <li class="active"><a href="{% url 'our_store:store' %}">OUR STORE</a></li> 
        <li><a href="{% url 'what_we_do-view' %}" >WHAT WE DO</a></li>
        <li><a href="{% url 'industries-view' %}" >INDUSTRIES</a></li>
        <li><a href="{% url 'get_in_touch-view' %} ">GET IN TOUCH</a></li>   
        <li><a href="{% url 'who_we_are-view' %}" >WHO WE ARE</a></li>
          <a href="{% url 'our_store:adminlogin' %}" class="btn btn-primary">Admin Login</a>
      </ul>
  </nav>
</body>

templates/main/pharmaceutical.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>pharmatucal</title>
    {% endblock title %}

{% block content %}
<br>
    <center><strong>
    <h1>RFID in Pharmatical</h1>
    </strong></center>
        <hr>
        <div class="ui grid">
            <br>
            <div class="row">
                <div class="col-md-6">
                    <img src={% static 'image/medical001.jpg' %}>
                </div>
                <div class="col-md-6">
                    <p>
                    <p>
                        <h1>RFID labels benefits manufacturers, hospitals and patients</h1>
                        Patient safety is paramount when it comes to pharmaceutical products and medical devices. 
                        That is why certain types of labels are mandatory for manufacturers, for instance to prevent 
                        counterfeit drugs or foods from being sold. Improved visibility along the entire delivery and 
                        value chain also increases economic efficiency for transport and stock levels.
                    </p>
                    <hr>
                    <p>
                        <h1> RFID labels increases protection against counterfeiting</h1>
                        Every year, product piracy costs the industry several billion US dollars. Profits are not only
                        impacted by the sales of counterfeit and manipulated medication. Pharmaceutics companies also 
                        pay the price of damaged reputations and illegitimate product-liability cases. Product marking
                        plays a key role in anti-counterfeiting measures.
                    </p>
                    <hr>
                    <strong>Tiny transponders</strong> in RFID labels store individual product information. If needed, the 
                            information can be quickly accessed for real-time tracking and authentication. Paired with 
                            special RFID readers, these labels can even be used to detect possible manipulation and serve 
                            as an effective deterrent.
                </div>
            </div>
        </div>
{% endblock content %}

templates/main/retail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>retail</title>
    {% endblock title %}
{% block content %}
    
    <br>
    <center>
    <h1>RFID in Retail</h1>
    </center>
    <hr>
    <div class="ui grid">
        <br>
        <div class="row">
            
            <div class="col-md-6">
                <img src={% static 'image/GS1au-banner-rfid-in-retail-848x250 03.jpg' %}>
                <!--<img src='image.jpg' alt="Image" height="42" width="42">.-->
            </div>

            <div class="col-md-6">
                <p>
                Radio Frequency Identification (RFID) has been on the immediate horizon for the last 
                decade. However, we are now at a point where several factors are driving the technology
                forward and forcing the hand of manufacturers and retailers. Retailers crave sources of 
                data to optimize their business; RFID creates a whole new set of data about their 
                in-store environments, product movement, and customer behavior. As a result, companies 
                that aren’t already piloting RFID are lagging the market, and those using the technology
                must continue to develop additional capabilities around it due to its potential for 
                massive cost savings and new revenue opportunities.
                </p>
                <hr>
                <p>
                <h1>RFID Technology Overview</h1>
                RFID systems are composed of tags and a reader to read them. The RFID tag has two components,
                a processor and an antenna. Tags can be active and use a battery, or passive and use power 
                from the reader. The reader can be handheld or stationary and can vary in size and strength 
                based on purpose. Tags can be on hangtags, stickers, or embedded in items. Tags can be given 
                a unique fingerprint to be tracked individually.
                </p>
            </div>
        </div>
    </div>
        
{% endblock content %}

templates/main/supply_chain.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    {% block title %}
    <title>supply_chain</title>
    {% endblock title %}
    <br>
    <center>
    <h1>RFID in Supply Chain</h1>
    </center>
    <hr>
        <div class="ui grid">
            <br>
            <div class="row">
                <div class="col-md-6">
                    <img src={% static 'image/LogisticNSupply.png' %}>
                </div>
                <div class="col-md-6">
                    <p>RFID systems are widely used to track intermediate bulk containers 
                    (IBCs) in the chemicals industry, stillages in automotive plants, and industrial tanks 
                    used to transport gases, oils and waste materials. By attaching RFID tags, containers can 
                    be electronically identified from metres away. The tags can be read by fixed scanners as 
                    they pass through doorways or key points in the production process, or by staff using 
                    handheld readers.
                    </p> 
                    <hr>
                    <p>Containers can be booked out automatically, assigned to a particular
                    customer and batch. They can be checked back in again and inspected just as easily and 
                    stocks can be audited quickly too. By replacing spreadsheets and manual processes, 
                    RFID systems save time and reduce errors. The data collected is automatically uploaded 
                    to a cloud-based system so anyone with access can see which IBCs are where, their history
                    and overall usage. Integration with back office systems is also easily achievable, 
                    allowing asset and ERP systems to be updated automatically.
                    </p>
    
                    <hr>
                    <p>
                        
                    </p>
                </div>
            </div>
        </div>
{% endblock content %}

templates/main/who_we_are.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

    <style>
        bg {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}
    </style>
    <br/>
    {% block title %}
    <title>WHo We Are</title>
    {% endblock title %}

    
    <div class="ui grid">
        <div class="row">
            <div class="col-md-6">
                        <div class="logo">
                            <img src= "{% static 'image/Logo001.jpg' %}" style="width:510px; height: 150px;">
                        </div>
            </div>
            <div class="col-md-6">
                        <div class="logo">
                            <img src= "{% static 'image/Logo001.jpg' %}" style="width:510px; height: 150px;">
                        </div>
            </div>
        </div>
        <div class="row">
            <div class="sixthin wide column">
                <div class="ui fluid card" style="background-color: rgba(18, 15, 26, 0.4) ">

                    <div class="content">
                        <!--<h1 style="text-align:center; color: black; font-size: 40px; margin-top: 275px;">-->
                            <strong><h1>Who we Are</h1></strong>
                        <strong><a style="color: black;">
                            We are a recently established RADIO FREQUENCY IDENTIFICATION business, 
                            we are established in a fast-growing African market. RFIDESIGN has been established in 2019 in Pretoria, 
                            Gauteng province, South Africa. We are dedicated to deliver high quality products to our customers, meanwhile, 
                            we insist our sense of society responsibility and environmental protection duty.
                            We thrive on bringing success in Information Technology industry through transparency, 
                            accountability and oversight and passionately and all this by learning from both our customers and our competitors each time we interact. 
                            We take the mission of promoting the popularity of RFID technology applications, 
                            realizing intelligent data collection, improving efficiency, reducing costs, and creating benefits for users.
                        </a></strong>
                    </div>
                </div>
            </div>  
        </div>
    </div> 
    {% endblock content %}

                                           